### ISSUE TITLE
How to train on non landmark dataset?

### ISSUE THREAD

**Issue by Mrtrl** [fmaglia/keras_rmac_plus#2]
Hi, fmaglia, Thanks for sharing the great code.
I'm interested in how to train on non landmark datasets by using your code? like deep fashion dataset ..
How should i prepare the dataset? 
Hopeing to get your help, Thank you !~

**Comment by fmaglia** [comment]
Hi Mrtrl,

if you want to use different datasets, you need to modify the functions: readTraining() and readTest() in utils.py in order to get from your file system the image of your own dataset.
For the dataset preparation, you need only to subdivide the dataset in two different folders: database (images used for the ranking calculation of each query image) and query images and then load them using the python script.
